spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/shieldgate
    password: ${POSTGRES_PASSWORD:changeme}
  data:
    redis:
      host: redis
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}